### ISSUE TITLE
Add pre-commit hooks, whatever you like

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#68]

**Comment by Vaaaaa** [comment]
Can I take this over?

**Comment by KevinHock** [comment]
@Vaaaaa Yes you can :) Feel free to look at https://github.com/python-security/pyt/pull/88/files for inspiration. Thank you 🙏

**Comment by Vaaaaa** [comment]
Thanks Kevin, I am new to this but I am keenly interested on this project. Please do help me with these, any specific hooks that should be added in order to handle files in future or any manual python script for any scenario or condition?. I have added hooks like `check-ast`  and `check-symlinks`, Correct me in case I am missing something.

**Comment by KevinHock** [comment]
Those plus the ones in the PR should be good. 👍 

If you're hoping to get more into PyT I would read the docs (incomplete but still good) and then try out 
https://github.com/python-security/pyt/issues/62 To get more exposure to how the interprocedural/ast visitor works. I'm about to change how PyT finds vulnerabilities in a pretty big way but after the current open PR is merged we can work together on the

**Comment by KevinHock** [comment]
(Typing on the train, accidentally closed.)

Work together on the vulnerabilities part. (E.g. The json output and stuff.)

**Comment by Vaaaaa** [comment]
Thanks Kevin, I will push the hook changes. I will be working on #62.

**Comment by KevinHock** [comment]
Awesome, I'll update my #62 issue description to be more helpful 👍

**Comment by KevinHock** [comment]
Thanks for your help on this @Vaaaaa
